<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        Product::truncate();


        $products = [
            // 📱 الموبايلات (30)
            [
                'name' => 'iPhone 15 Pro Max',
                'slug' => 'iphone-15-pro-max',
                'description' => 'Apple iPhone 15 Pro Max with A17 Pro chip, 6.7-inch OLED display, 48MP triple camera system.',
                'price' => 1199.99,
                'image_url' => 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro-max.jpg',
                'stock' => 50,
                'category' => 'mobile',

            ],
            [
                'name' => 'Xiaomi 14 Pro',
                'slug' => 'xiaomi-14-pro',
                'description' => 'Xiaomi 14 Pro with Snapdragon 8 Gen 3, 50MP Leica cameras, 6.73-inch AMOLED 120Hz.',
                'price' => 899.99,
                'image_url' => 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14-pro.jpg',
                'stock' => 35,
                'category' => 'mobile',
            ],
            [
                'name' => 'OnePlus 12',
                'slug' => 'oneplus-12',
                'description' => 'OnePlus 12 with Snapdragon 8 Gen 3, Hasselblad cameras, 6.82-inch AMOLED 120Hz.',
                'price' => 949.99,
                'image_url' => 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-12.jpg',
                'stock' => 30,
                'category' => 'mobile',
            ],

            [
                'name' => 'iPhone 14 Pro Max',
                'slug' => Str::slug('iPhone 14 Pro Max'),
                'description' => 'Apple flagship with A16 Bionic, 6.7-inch OLED, and ProMotion display.',
                'price' => 1200,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-max-1.jpg',
                'stock' => 50,
                'category' => 'mobile',
            ],
            [
                'name' => 'iPhone 13 Pro Max',
                'slug' => Str::slug('iPhone 13 Pro Max'),
                'description' => 'Apple iPhone 13 Pro Max with A15 Bionic and 120Hz ProMotion display.',
                'price' => 1000,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-pro-max-1.jpg',
                'stock' => 40,
                'category' => 'mobile',
            ],
            [
                'name' => 'iPhone 12 Pro',
                'slug' => Str::slug('iPhone 12 Pro'),
                'description' => 'Apple iPhone 12 Pro with A14 Bionic and triple camera system.',
                'price' => 850,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-pro-max-1.jpg',
                'stock' => 30,
                'category' => 'mobile',
            ],
            [
                'name' => 'OnePlus 10 Pro',
                'slug' => Str::slug('OnePlus 10 Pro'),
                'description' => 'OnePlus 10 Pro with Snapdragon 8 Gen 1, 6.7-inch AMOLED, and Hasselblad tuning.',
                'price' => 650,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-10-pro-1.jpg',
                'stock' => 40,
                'category' => 'mobile',
            ],
            [
                'name' => 'OnePlus 9 Pro',
                'slug' => Str::slug('OnePlus 9 Pro'),
                'description' => 'OnePlus 9 Pro with Snapdragon 888, 120Hz AMOLED, and Hasselblad cameras.',
                'price' => 550,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-9-pro-1.jpg',
                'stock' => 35,
                'category' => 'mobile',
            ],
            [
                'name' => 'Oppo Find X5 Pro',
                'slug' => Str::slug('Oppo Find X5 Pro'),
                'description' => 'Oppo Find X5 Pro with Snapdragon 8 Gen 1 and Hasselblad cameras.',
                'price' => 850,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/oppo/oppo-find-x5-pro-1.jpg',
                'stock' => 40,
                'category' => 'mobile',
            ],
            [
                'name' => 'Oppo Reno8 Pro',
                'slug' => Str::slug('Oppo Reno8 Pro'),
                'description' => 'Oppo Reno8 Pro with Dimensity 8100-Max and 6.7-inch AMOLED.',
                'price' => 600,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/oppo/oppo-reno8-pro-1.jpg',
                'stock' => 30,
                'category' => 'mobile',
            ],
            [
                'name' => 'Huawei P50 Pro',
                'slug' => Str::slug('Huawei P50 Pro'),
                'description' => 'Huawei P50 Pro with Snapdragon 888/Kirin 9000 and Leica quad cameras.',
                'price' => 750,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/huawei/huawei-p50-pro-1.jpg',
                'stock' => 35,
                'category' => 'mobile',
            ],
            [
                'name' => 'Huawei Mate 40 Pro',
                'slug' => Str::slug('Huawei Mate 40 Pro'),
                'description' => 'Huawei Mate 40 Pro with Kirin 9000, 6.76-inch OLED, and 50MP Ultra Vision camera.',
                'price' => 700,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/huawei/huawei-mate-40-pro-1.jpg',
                'stock' => 30,
                'category' => 'mobile',
            ],
            [
                'name' => 'Realme GT2 Pro',
                'slug' => Str::slug('Realme GT2 Pro'),
                'description' => 'Realme GT2 Pro with Snapdragon 8 Gen 1, AMOLED display, and 150° ultra-wide camera.',
                'price' => 650,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/realme/realme-gt2-pro-1.jpg',
                'stock' => 35,
                'category' => 'mobile',
            ],
            [
                'name' => 'Sony Xperia 1 IV',
                'slug' => Str::slug('Sony Xperia 1 IV'),
                'description' => 'Sony Xperia 1 IV with Snapdragon 8 Gen 1, 4K OLED display, and pro-grade cameras.',
                'price' => 1200,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/sony/sony-xperia-1-iv-1.jpg',
                'stock' => 20,
                'category' => 'mobile',
            ],
            [
                'name' => 'Sony Xperia 5 IV',
                'slug' => Str::slug('Sony Xperia 5 IV'),
                'description' => 'Sony Xperia 5 IV with Snapdragon 8 Gen 1, compact OLED display, and triple camera.',
                'price' => 950,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/sony/sony-xperia-5-iv-1.jpg',
                'stock' => 25,
                'category' => 'mobile',
            ],
            [
                'name' => 'Asus ROG Phone 7',
                'slug' => Str::slug('Asus ROG Phone 7'),
                'description' => 'Gaming beast with Snapdragon 8 Gen 2, 165Hz AMOLED, and massive battery.',
                'price' => 1100,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/asus/asus-rog-phone-7-1.jpg',
                'stock' => 30,
                'category' => 'mobile',
            ],
            [
                'name' => 'Asus Zenfone 9',
                'slug' => Str::slug('Asus Zenfone 9'),
                'description' => 'Compact flagship with Snapdragon 8+ Gen 1, 5.9-inch AMOLED, and dual cameras.',
                'price' => 700,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/asus/asus-zenfone-9-1.jpg',
                'stock' => 25,
                'category' => 'mobile',
            ],

            [
                'name' => 'Motorola Edge 40 Pro',
                'slug' => Str::slug('Motorola Edge 40 Pro'),
                'description' => 'Motorola Edge 40 Pro with Snapdragon 8 Gen 2, 165Hz AMOLED, and 68W charging.',
                'price' => 850,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/motorola/motorola-edge-40-pro-1.jpg',
                'stock' => 30,
                'category' => 'mobile',
            ],
            [
                'name' => 'Samsung Galaxy Z Fold4',
                'slug' => Str::slug('Samsung Galaxy Z Fold4'),
                'description' => 'Foldable flagship with Snapdragon 8+ Gen 1 and 7.6-inch foldable AMOLED.',
                'price' => 1800,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-z-fold4-1.jpg',
                'stock' => 20,
                'category' => 'mobile',
            ],
            [
                'name' => 'Samsung Galaxy Z Flip4',
                'slug' => Str::slug('Samsung Galaxy Z Flip4'),
                'description' => 'Compact foldable with Snapdragon 8+ Gen 1 and 6.7-inch AMOLED.',
                'price' => 999,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-z-flip4-1.jpg',
                'stock' => 35,
                'category' => 'mobile',
            ],
            [
                'name' => 'Google Pixel 7 Pro',
                'slug' => Str::slug('Google Pixel 7 Pro'),
                'description' => 'Google Pixel 7 Pro with Tensor G2, triple camera, and 6.7-inch OLED.',
                'price' => 900,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/google/google-pixel-7-pro-1.jpg',
                'stock' => 40,
                'category' => 'mobile',
            ],
            [
                'name' => 'Google Pixel 6 Pro',
                'slug' => Str::slug('Google Pixel 6 Pro'),
                'description' => 'Google Pixel 6 Pro with Tensor chip, 6.7-inch OLED, and 50MP main camera.',
                'price' => 700,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/google/google-pixel-6-pro-1.jpg',
                'stock' => 35,
                'category' => 'mobile',
            ],
            [
                'name' => 'Google Pixel 5',
                'slug' => Str::slug('Google Pixel 5'),
                'description' => 'Google Pixel 5 with Snapdragon 765G, 6-inch OLED, and excellent cameras.',
                'price' => 500,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/google/google-pixel-5-1.jpg',
                'stock' => 25,
                'category' => 'mobile',
            ],
            [
                'name' => 'Xiaomi 13 Pro',
                'slug' => Str::slug('Xiaomi 13 Pro'),
                'description' => 'Xiaomi 13 Pro with Snapdragon 8 Gen 2, Leica camera system, and 120W charging.',
                'price' => 800,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-13-pro-1.jpg',
                'stock' => 50,
                'category' => 'mobile',
            ],
            [
                'name' => 'Xiaomi 12 Pro',
                'slug' => Str::slug('Xiaomi 12 Pro'),
                'description' => 'Xiaomi 12 Pro with Snapdragon 8 Gen 1, AMOLED display, and 120W fast charging.',
                'price' => 700,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-12-pro-1.jpg',
                'stock' => 40,
                'category' => 'mobile',
            ],
            [
                'name' => 'Xiaomi Mi 11 Ultra',
                'slug' => Str::slug('Xiaomi Mi 11 Ultra'),
                'description' => 'Xiaomi Mi 11 Ultra with Snapdragon 888, 120Hz AMOLED, and secondary rear display.',
                'price' => 650,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-mi-11-ultra-1.jpg',
                'stock' => 30,
                'category' => 'mobile',
            ],
            [
                'name' => 'OnePlus 11',
                'slug' => Str::slug('OnePlus 11'),
                'description' => 'OnePlus 11 with Snapdragon 8 Gen 2, Hasselblad cameras, and 100W fast charging.',
                'price' => 750,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-11-1.jpg',
                'stock' => 55,
                'category' => 'mobile',
            ],

            [
                'name' => 'Motorola Moto G200',
                'slug' => Str::slug('Motorola Moto G200'),
                'description' => 'Motorola Moto G200 with Snapdragon 888+, 144Hz LCD, and 5000mAh battery.',
                'price' => 600,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/motorola/motorola-moto-g200-1.jpg',
                'stock' => 35,
                'category' => 'mobile',
            ],
                        [
                'name' => 'iPhone 11 Pro Max',
                'slug' => Str::slug('iPhone 11 Pro Max'),
                'description' => 'Apple iPhone 11 Pro Max with A13 Bionic and 6.5-inch OLED display.',
                'price' => 700,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-11-pro-max-1.jpg',
                'stock' => 25,
                'category' => 'mobile',
            ],
            [
                'name' => 'Samsung Galaxy S23 Ultra',
                'slug' => Str::slug('Samsung Galaxy S23 Ultra'),
                'description' => 'Samsung flagship with Snapdragon 8 Gen 2, 200MP camera, and S-Pen.',
                'price' => 1100,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s23-ultra-1.jpg',
                'stock' => 60,
                'category' => 'mobile',
            ],
            [
                'name' => 'Samsung Galaxy S22 Ultra',
                'slug' => Str::slug('Samsung Galaxy S22 Ultra'),
                'description' => 'Samsung Galaxy S22 Ultra with Exynos 2200/Snapdragon 8 Gen 1 and 108MP camera.',
                'price' => 950,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-ultra-1.jpg',
                'stock' => 50,
                'category' => 'mobile',
            ],
            [
                'name' => 'Samsung Galaxy S21 Ultra',
                'slug' => Str::slug('Samsung Galaxy S21 Ultra'),
                'description' => 'Samsung Galaxy S21 Ultra with 6.8-inch AMOLED and 108MP quad camera.',
                'price' => 800,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s21-ultra-1.jpg',
                'stock' => 45,
                'category' => 'mobile',
            ],
            [
                'name' => 'Google Pixel 8 Pro',
                'slug' => 'google-pixel-8-pro',
                'description' => 'Google Pixel 8 Pro with Google Tensor G3, 50MP triple cameras, 6.7-inch LTPO OLED.',
                'price' => 999.99,
                'image_url' => 'https://fdn2.gsmarena.com/vv/bigpic/google-pixel8-pro.jpg',
                'stock' => 25,
                'category' => 'mobile',
            ],
            [
                'name' => 'Samsung Galaxy S24 Ultra',
                'slug' => 'samsung-galaxy-s24-ultra',
                'description' => 'Samsung Galaxy S24 Ultra with Snapdragon 8 Gen 3, 200MP main camera, 6.8-inch AMOLED display.',
                'price' => 1099.99,
                'image_url' => 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-ultra.jpg',
                'stock' => 40,
                'category' => 'mobile',
            ],
            [
                'name' => 'Samsung Galaxy S24+',
                'slug' => 'samsung-galaxy-s24-plus',
                'description' => 'Samsung Galaxy S24+ with Snapdragon 8 Gen 3, 6.6-inch AMOLED display, and 50MP main camera.',
                'price' => 899.99,
                'image_url' => 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-plus.jpg',
                'stock' => 45,
                'category' => 'mobile',
            ],
            [
                'name' => 'Samsung Galaxy S24',
                'slug' => 'samsung-galaxy-s24',
                'description' => 'Samsung Galaxy S24 with Snapdragon 8 Gen 3, 6.1-inch AMOLED display, and 50MP main camera.',
                'price' => 799.99,
                'image_url' => 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24.jpg',
                'stock' => 50,
                'category' => 'mobile',
            ],


        // ⌚ الساعات (20)

            [
                'name' => 'Fossil Gen 6',
                'slug' => Str::slug('Fossil Gen 6'),
                'description' => 'Fossil Gen 6 smartwatch with Wear OS by Google, Snapdragon processor, and customizable dials.',
                'price' => 299.00,
                'image_url' => 'https://fossil.scene7.com/is/image/FossilPartners/FTW4061_main?$sfcc_fos_large$',
                'stock' => 35,
                'category' => 'watch',
            ],
            [
                'name' => 'Samsung Galaxy Watch 5 Pro',
                'slug' => Str::slug('Samsung Galaxy Watch 5 Pro'),
                'description' => 'Samsung Galaxy Watch 5 Pro with advanced health tracking, GPS, and durable design.',
                'price' => 449.99,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-watch5-pro-1.jpg',
                'stock' => 40,
                'category' => 'watch',
            ],
            [
                'name' => 'Samsung Galaxy Watch 4 Classic',
                'slug' => Str::slug('Samsung Galaxy Watch 4 Classic'),
                'description' => 'Samsung Galaxy Watch 4 Classic with rotating bezel, Wear OS, and health monitoring features.',
                'price' => 349.99,
                'image_url' => 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-watch4-classic-1.jpg',
                'stock' => 45,
                'category' => 'watch',
            ],

            [
                'name' => 'Apple Watch Series 9',
                'slug' => Str::slug('Apple Watch Series 9'),
                'description' => 'Apple Watch Series 9 with advanced health tracking, GPS, and Always-On Retina Display.',
                'price' => 399.00,
                'image_url' => 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MQE53_VW_34FR+watch-case-45-aluminum-midnight-nc-s9_VW_34FR+watch-face-45-aluminum-midnight-s9_VW_34FR_GEO_EMEA?wid=400&hei=400&fmt=jpeg',
                'stock' => 50,
                'category' => 'watch',
            ],
            [
                'name' => 'Samsung Galaxy Watch 6',
                'slug' => Str::slug('Samsung Galaxy Watch 6'),
                'description' => 'Samsung Galaxy Watch 6 with sleep coaching, heart rate monitor, and AMOLED display.',
                'price' => 329.00,
                'image_url' => 'https://image-us.samsung.com/SamsungUS/home/mobile/wearables/pdp/sm-r930nzkaxaa/gallery/2023/Samsung-Galaxy-Watch6-40mm-BT-Graphite-SMR930NZKAXAA-01.jpg?$product-details-jpg$',
                'stock' => 60,
                'category' => 'watch',
            ],
            [
                'name' => 'Garmin Venu 3',
                'slug' => Str::slug('Garmin Venu 3'),
                'description' => 'Garmin Venu 3 with fitness tracking, GPS, and AMOLED touchscreen.',
                'price' => 449.00,
                'image_url' => 'https://static.garmincdn.com/en/products/010-02784-00/g/cf-lg-0f87c2b6-60f8-4f53-bb82-b57bb9c49da2.jpg',
                'stock' => 40,
                'category' => 'watch',
            ],
            [
                'name' => 'Fitbit Versa 4',
                'slug' => Str::slug('Fitbit Versa 4'),
                'description' => 'Fitbit Versa 4 with daily readiness score, heart health monitoring, and 6-day battery life.',
                'price' => 229.95,
                'image_url' => 'https://static-ec.fitbit.com/content/assets/versa-4/versa-4-carousel-1.jpg',
                'stock' => 70,
                'category' => 'watch',
            ],
            [
                'name' => 'Huawei Watch GT 4',
                'slug' => Str::slug('Huawei Watch GT 4'),
                'description' => 'Huawei Watch GT 4 with ultra-long battery life, health monitoring, and sleek design.',
                'price' => 249.00,
                'image_url' => 'https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/pdp/wearables/watch-gt-4/gt4-46mm-green.png',
                'stock' => 55,
                'category' => 'watch',
            ],
            [
                'name' => 'Amazfit GTR 4',
                'slug' => Str::slug('Amazfit GTR 4'),
                'description' => 'Amazfit GTR 4 with advanced fitness tracking and AMOLED display.',
                'price' => 199.00,
                'image_url' => 'https://static.amazfit.com/product/gtr4/images/gallery/black/1.jpg',
                'stock' => 65,
                'category' => 'watch',
            ],

            [
                'name' => 'TicWatch Pro 5',
                'slug' => Str::slug('TicWatch Pro 5'),
                'description' => 'TicWatch Pro 5 with dual display technology and long-lasting battery.',
                'price' => 349.00,
                'image_url' => 'https://m.media-amazon.com/images/I/71Md6V1zUqL._AC_SL1500_.jpg',
                'stock' => 45,
                'category' => 'watch',
            ],
            [
                'name' => 'Suunto 9 Peak Pro',
                'slug' => Str::slug('Suunto 9 Peak Pro'),
                'description' => 'Suunto 9 Peak Pro with military-grade durability and GPS navigation.',
                'price' => 499.00,
                'image_url' => 'https://www.suunto.com/globalassets/suunto-pdp/ss050928000/suunto-9-peak-pro-black-hero.png',
                'stock' => 25,
                'category' => 'watch',
            ],
            [
                'name' => 'Withings ScanWatch',
                'slug' => Str::slug('Withings ScanWatch'),
                'description' => 'Withings ScanWatch with ECG, SpO2, and long battery life.',
                'price' => 279.00,
                'image_url' => 'https://www.withings.com/media/0c/6b/0c6be3b7482fbd4d4a97e9f544f69bbefc0662f7.png',
                'stock' => 30,
                'category' => 'watch',
            ],
            [
                'name' => 'Polar Grit X Pro',
                'slug' => Str::slug('Polar Grit X Pro'),
                'description' => 'Polar Grit X Pro with outdoor navigation and sports performance tracking.',
                'price' => 499.00,
                'image_url' => 'https://www.polar.com/sites/default/files/media-images/2021-10/polar-grit-x-pro.png',
                'stock' => 20,
                'category' => 'watch',
            ],
            [
                'name' => 'Amazfit T-Rex 2',
                'slug' => Str::slug('Amazfit T-Rex 2'),
                'description' => 'Amazfit T-Rex 2 rugged outdoor smartwatch with dual-band GPS.',
                'price' => 229.00,
                'image_url' => 'https://static.amazfit.com/product/trex2/images/black-1.jpg',
                'stock' => 45,
                'category' => 'watch',
            ],
            [
                'name' => 'Casio G-Shock Move',
                'slug' => Str::slug('Casio G-Shock Move'),
                'description' => 'Casio G-Shock Move with shock resistance and fitness tracking features.',
                'price' => 150.00,
                'image_url' => 'https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/G/GBD/GBD-100/GBD-100-1/Gallery/GBD-100-1.png',
                'stock' => 80,
                'category' => 'watch',
            ],
            [
                'name' => 'Skagen Falster Gen 6',
                'slug' => Str::slug('Skagen Falster Gen 6'),
                'description' => 'Skagen Falster Gen 6 smartwatch with minimalist design and Wear OS.',
                'price' => 295.00,
                'image_url' => 'https://www.skagen.com/on/demandware.static/-/Sites-masterCatalog_Fossil/default/dwdb63cb48/images/Skagen/sku/SKT5303_main.jpg',
                'stock' => 35,
                'category' => 'watch',
            ],
            [
                'name' => 'Mobvoi TicWatch E3',
                'slug' => Str::slug('Mobvoi TicWatch E3'),
                'description' => 'Mobvoi TicWatch E3 with Google Assistant, fitness tracking, and GPS.',
                'price' => 199.00,
                'image_url' => 'https://m.media-amazon.com/images/I/71s2y0Cl5cL._AC_SL1500_.jpg',
                'stock' => 40,
                'category' => 'watch',
            ],
            [
                'name' => 'Diesel Griffed Gen 6',
                'slug' => Str::slug('Diesel Griffed Gen 6'),
                'description' => 'Diesel Griffed Gen 6 smartwatch with bold design and smart features.',
                'price' => 350.00,
                'image_url' => 'https://diesel.scene7.com/is/image/Diesel/DT2008_main?$sfcc_fos_large$',
                'stock' => 25,
                'category' => 'watch',
            ],
            [
                'name' => 'Michael Kors Gen 6 Bradshaw',
                'slug' => Str::slug('Michael Kors Gen 6 Bradshaw'),
                'description' => 'Michael Kors Gen 6 Bradshaw smartwatch with luxury design and smart features.',
                'price' => 375.00,
                'image_url' => 'https://michaelkors.scene7.com/is/image/MichaelKors/MKT5133-0001_1?$large$',
                'stock' => 20,
                'category' => 'watch',
            ],
            [
                'name' => 'Tag Heuer Connected',
                'slug' => Str::slug('Tag Heuer Connected'),
                'description' => 'Tag Heuer Connected luxury smartwatch with Wear OS and premium build.',
                'price' => 1800.00,
                'image_url' => 'https://www.tagheuer.com/on/demandware.static/-/Sites-tagheuer-master/default/dwd83a1edc/TAG-Heuer-Connected-Watch-SBR8A10.BT6259-1.png',
                'stock' => 10,
                'category' => 'watch',
            ],
            [
                'name' => 'Montblanc Summit 3',
                'slug' => Str::slug('Montblanc Summit 3'),
                'description' => 'Montblanc Summit 3 smartwatch with premium craftsmanship and Wear OS.',
                'price' => 1290.00,
                'image_url' => '',
                'stock' => 8,

                'category' => 'watch',
            ],
            [
                'name' => 'Garmin Forerunner 955',
                'slug' => Str::slug('Garmin Forerunner 955'),
                'description' => 'Garmin Forerunner 955 with advanced running metrics and GPS navigation.',
                'price' => 499.00,
                'image_url' => 'https://static.garmincdn.com/en/products/010-02638-00/g/cf-lg-0eab06d3-7e61-4a3e-b823-3b04f8cde99a.jpg',
                'stock' => 30,
                'category' => 'watch',
            ],
        ];

        Product::insert($products);
    }
}
